name: beacon_scanner_ios
description: The iOS implementation of beacon_scanner_platform_interface
repository: https://github.com/Gigas002/beacon_scanner/tree/main/beacon_scanner_ios
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

flutter:
  plugin:
    implements: beacon_scanner
    platforms:
      ios:
        pluginClass: BeaconScannerPlugin
        dartPluginClass: BeaconScannerIOS

dependencies:
  flutter:
    sdk: flutter
  beacon_scanner_platform_interface:
    path: ../beacon_scanner_platform_interface

dev_dependencies:
  flutter_lints: any
