name: beacon_scanner_example
description: "Demonstrates how to use the beacon_scanner plugin."
publish_to: 'none'

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  beacon_scanner:
    path: ../

flutter:
  uses-material-design: true
