name: beacon_scanner
description: A Flutter plugin for scanning bluetooth low energy iBeacon frames.
  Works also in background.
repository: https://github.com/Gigas002/beacon_scanner/tree/main/beacon_scanner
issue_tracker: https://github.com/Gigas002/beacon_scanner/issues?q=is%3Aissue+is%3Aopen
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: beacon_scanner_android
      ios:
        default_package: beacon_scanner_ios

dependencies:
  flutter:
    sdk: flutter
  beacon_scanner_android:
    path: ../beacon_scanner_android
  beacon_scanner_ios:
    path: ../beacon_scanner_ios
  beacon_scanner_platform_interface:
    path: ../beacon_scanner_platform_interface

dev_dependencies:
  flutter_lints: any
  plugin_platform_interface: any
