name: beacon_scanner_platform_interface
description: A common platform interface for the beacon_scanner_platform_interface plugin.
repository: https://github.com/Gigas002/beacon_scanner/tree/main/beacon_scanner_platform_interface
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: any
  meta: any

dev_dependencies:
  flutter_lints: any
