name: beacon_scanner_android
description: The Android implementation of beacon_scanner_platform_interface
repository: https://github.com/Gigas002/beacon_scanner/tree/main/beacon_scanner_android
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

flutter:
  plugin:
    implements: beacon_scanner
    platforms:
      android:
        package: com.lukangagames.plugins.beaconscanner
        pluginClass: BeaconScannerPlugin
        dartPluginClass: BeaconScannerAndroid

dependencies:
  flutter:
    sdk: flutter
  beacon_scanner_platform_interface:
    path: ../beacon_scanner_platform_interface

dev_dependencies:
  flutter_lints: any
